const ADD_TO_CART = "ADD_TO_CART";  // adds a element to the cart using it's id

const FETCH_ALL_COMPUTERS_SUCCESS = "FETCH_ALL_COMPUTERS_SUCCESS";
const FETCH_ALL_KEYBOARDS_SUCCESS = "FETCH_ALL_KEYBOARDS_SUCCESS";
const FETCH_ALL_SCREENS_SUCCESS = "FETCH_ALL_SCREENS_SUCCESS";
const FETCH_ALL_MOUSES_SUCCESS = "FETCH_ALL_MOUSES_SUCCESS";

const FETCH_ALL_COMPUTERS_REQUEST = "FETCH_ALL_COMPUTERS_REQUEST";
const FETCH_ALL_KEYBOARDS_REQUEST = "FETCH_ALL_KEYBOARDS_REQUEST";
const FETCH_ALL_SCREENS_REQUEST = "FETCH_ALL_SCREENS_REQUEST";
const FETCH_ALL_MOUSES_REQUEST = "FETCH_ALL_MOUSES_REQUEST";