export const FETCH_ALL_COMPUTERS_SUCCESS = "FETCH_ALL_COMPUTERS_SUCCESS";
export const FETCH_ALL_KEYBOARDS_SUCCESS = "FETCH_ALL_KEYBOARDS_SUCCESS";
export const FETCH_ALL_SCREENS_SUCCESS = "FETCH_ALL_SCREENS_SUCCESS";
export const FETCH_ALL_MOUSES_SUCCESS = "FETCH_ALL_MOUSES_SUCCESS";
export const FETCH_ALL_COMPUTERS_REQUEST = "FETCH_ALL_COMPUTERS_REQUEST";
export const FETCH_ALL_KEYBOARDS_REQUEST = "FETCH_ALL_KEYBOARDS_REQUEST";
export const FETCH_ALL_SCREENS_REQUEST = "FETCH_ALL_SCREENS_REQUEST";
export const FETCH_ALL_MOUSES_REQUEST = "FETCH_ALL_MOUSES_REQUEST";